### ISSUE TITLE
XLHTTPServerConnection did {opne|close} over IPv6

### ISSUE THREAD

**Issue by Khronoss** [swisspol/XLFacility#12]
Hi,

When running the HTTP logger, all logs are being hard to see because the logger keep saying in loop : 
GCDTCPServer did connect to peer at "::1c1e:1f90:0:0" (59433)
XLHTTPServerConnection did open over IPv6 from ::a7b3:9eb9:85d9:bf (8080) to ::1c1e:1f90:0:0 (59433)
XLHTTPServerConnection did close over IPv6 from ::a7b3:9eb9:85d9:bf (8080) to ::1c1e:1f90:0:0 (59433)
GCDTCPServer did disconnect from peer at "::1c1e:1f90:0:0" (59433)

here is a screenshot of the results
![screen shot 2015-07-24 at 10 16 15](https://cloud.githubusercontent.com/assets/4353229/8870285/17175616-31ed-11e5-855d-9495683b77cc.png)

You can see that between all those "open/close connection" lines, there are 2 or 3 lines of code pretty hard to see at the first sight

all I do in my code is calling this line in my appDelegate:DidFinishedLaunching:

    [XLSharedFacility addLogger:[[XLHTTPServerLogger alloc] init]];

and then, I use those macros to log my events:

    XLOG_DEBUG(...), XLOG_INFO(...)

Is there any way to prevent it ?

**Comment by swisspol** [comment]
That's the problem: https://github.com/swisspol/XLFacility/blob/master/GCDTelnetServer/GCDNetworking/GCDNetworking/GCDTCPConnection.m#L401 and https://github.com/swisspol/XLFacility/blob/master/GCDTelnetServer/GCDNetworking/GCDNetworking/GCDTCPConnection.m#L405

If you build `Release` instead of `Debug`, or if you set the log level above `DEBUG` the problem will go away - but then you can't use the `DEBUG` level anymore...

**Comment by Khronoss** [comment]
Haaaa now I see =) I just thought it was a kind of bug =X Thanks ! \o
